# encoding: utf-8

# Coindesk API client settings
API_CLIENT_VERSION = '0.1.0'
API_PROTOCOL = 'https'
API_HOST = 'api.coindesk.com'
API_PATH = '/v1/bpi'
API_CURRENTPRICE_DATA_TYPE = 'currentprice'
API_HISTORICAL_DATA_TYPE = 'historical'
API_SUPPORTED_CURRENCIES_DATA_TYPE = 'supported-currencies'
API_CURRENTPRICE_ENDPOINT = f'{API_CURRENTPRICE_DATA_TYPE}' + '{currency}.json'
API_HISTORICAL_ENDPOINT = f'{API_HISTORICAL_DATA_TYPE}/close.json'
API_SUPPORTED_CURRENCIES_ENDPOINT = f'{API_SUPPORTED_CURRENCIES_DATA_TYPE}.json'
API_ENDPOINTS = {
    API_CURRENTPRICE_DATA_TYPE: API_CURRENTPRICE_ENDPOINT,
    API_HISTORICAL_DATA_TYPE: API_HISTORICAL_ENDPOINT,
    API_SUPPORTED_CURRENCIES_DATA_TYPE: API_SUPPORTED_CURRENCIES_ENDPOINT,
}

# Coindesk API valid parameters
INDEX_PARAM = 'index'
CURRENCY_PARAM = 'currency'
START_PARAM = 'start'
END_PARAM = 'end'
FOR_PARAM = 'for'
VALID_DATA_TYPES = [
    API_CURRENTPRICE_DATA_TYPE,
    API_HISTORICAL_DATA_TYPE,
]
VALID_CURRENTPRICE_PARAMS = [
    CURRENCY_PARAM,
]
VALID_HISTORICAL_PARAMS = [
    INDEX_PARAM,
    CURRENCY_PARAM,
    START_PARAM,
    END_PARAM,
    FOR_PARAM,
]
VALID_INDEX = [
    'USD',
    'CNY',
]
VALID_FOR = [
    'yesterday',
]
